config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create] do
    # member do
      resources :bookmarks, only: [:new, :create, :destroy]
    # end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, :dependent => :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    # @movie = Movie.find(params[:movie_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @list = List.find(params[:list_id])
    # @movie = Movie.find(params[:movie_id])
    @bookmark.list = @list
    # @movie.list = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    # bookmark = Bookmark.find
    @list = List.find(params[:list_id])
    bookmark.list = @list
    bookmark.destroy

    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:list_id, :movie_id, :comment)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Create a bookmark</h1>
  <p><%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %></p>
  <p><%= link_to "Back to #{@list.name}", list_path(@list), class: "btn btn-primary" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
<h1>My lists</h1>
  <% @lists.each do |list| %>
    <!-- <li><%= link_to list.name, list_path(list) %></li> -->
    <div class="card" style="width: 18rem;">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= list.name %></h5>
        <%= link_to "View list", list_path(list), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

<p><%= link_to "Create a list", new_list_path, class: "btn btn-primary" %></p>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Create a new list</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= f.input :photo, as: :file %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
  <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
  <p><h3>Bookmarks</h3>
  <% @list.bookmarks.each do |bookmark| %>
    <li><%= bookmark.movie.title %> | <%= bookmark.comment %> | <%= link_to "Delete bookmark", list_bookmark_path(@list, bookmark), method: :delete,
            data: { confirm: "Are you sure?"}, class: "btn btn-primary"  %></li>
  <% end %></p>

  <p><%= link_to "Add a bookmark", new_list_bookmark_path(@list), class: "btn btn-primary" %></p>
  <p><%= link_to "Back to list", lists_path, class: "btn btn-primary" %></p>
</div>